services:
  - type: web
    name: fundflow
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn FundFlow.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fundflow_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: fundflow_db
    databaseName: fundflow
    plan: free
