# Generated by Django 5.1.6 on 2025-05-06 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_limit_period_category_spending_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-end_date']},
        ),
        migrations.AddField(
            model_name='category',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='finance.financialgoal'),
        ),
        migrations.AddField(
            model_name='category',
            name='linked_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_categories', to='finance.financialgoal'),
        ),
    ]
